name: 'Container Image Builder'

on:
  workflow_dispatch:
  push:
    branches: [ "*" ]

jobs:
  releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # # Tmate ##
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - id: release
        name: Set Releases
        shell: bash
        run: |
          # Set Releases
          releases=""
          git fetch --depth=2
          for release in $(git diff --name-only HEAD HEAD~1 | cut -f 1 -d \/ | sed '/.git/d;/action/d' | sort -u); do
            echo "R=$release"
            releases+="$release,"
          done

          # Remover a ultima virgula+espaço das releases
          releases=${releases%,}
          releases=$(tr -d '\n' <<< $releases | jq -R -s -c 'split(",")')

          echo "relesesJson = $releases"

          echo "releases=$releases" >> $GITHUB_OUTPUT
          echo "releaseTag=$(date +%Y%m%d.%H%M)" >> $GITHUB_OUTPUT
    outputs:
      releaseName: ${{ steps.release.outputs.releases }}
      releaseTag: ${{ steps.release.outputs.releaseTag }}

  build-release:
    runs-on: ubuntu-22.04
    needs: [releases]
    strategy:
      matrix:
        releases: ${{ fromJSON(needs.releases.outputs.releaseName) }}
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Releases
        uses: gitbarnabedikartola/container-images@main
        with:
          releaseName: ${{ matrix.releases }}
          releaseTag: ${{ needs.releases.outputs.releaseTag }}
          registry: docker.io
          registryUser: ${{ secrets.DOCKER_USERNAME }}
          registryPassword: ${{ secrets.DOCKER_PASSWORD }}
          registryProject: 'barnabenimbus'
          archs: 'linux/amd64,linux/arm64'
